### ISSUE TITLE
crud em nodejs com as camadas de projeto

### ISSUE THREAD

**Issue by ghost** [Felipe-Cll/crud-nodejs#1]
Boa noite amigo, fiz de forma que consiga entender de como vai funcionar essa aplicação respeitando as camadas de projeto

- controller
- routes
- models
- inde.js

criei uma branch nova_ideia

**Comment by Felipe-Cll** [comment]
Salve Vinicius! Agradeço a ajuda, o projeto está bem no começo mesmo, estava testando com o Insomnia e agora estou manipulando com Mongodb. Aos poucos vai pegando forma! 😁
